services:
  server:
    container_name: server
    image: node:18-alpine
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  data:
