# fly.toml app configuration file generated for audiophile-e-commerce-server on 2023-08-13T08:57:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "audiophile-e-commerce-server"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
