name: Backend CD Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build TypeScript
        run: |
          cd server
          sudo yarn install --frozen-lockfile
          yarn build

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly
        run: |
          cd server
          fly deploy --access-token ${{ secrets.FLY_AUTH_TOKEN }}
